version: "3.9"

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

  web:
    build: ./giffres_lettres
    command: uwsgi --ini uwsgi/app.ini
    volumes:
      - /tmp
      - static_volume:/home/app/web/static
    env_file:
      - ./.env
    depends_on:
      - db

  nginx:
    build: ./nginx
    ports:
      - 8002:80
    volumes_from:
      - web
      # ssl
      - /etc/letsencrypt/live/pelicode.net/fullchain.pem:/etc/nginx/fullchain.pem
      - /etc/letsencrypt/live/pelicode.net/privkey.pem:/etc/nginx/privkey.pem

volumes:
  postgres_data:
  static_volume:
